# Generated by Django 3.2.3 on 2021-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
