# Generated by Django 3.2.3 on 2021-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_roomtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='marked_for_housekeep',
            field=models.BooleanField(default=False),
        ),
    ]
